//! The one deterministic generator every workload draws from.
//!
//! Xorshift64*, which is enough for choosing shapes and bytes and is
//! reproducible from the seed printed in every report. It lives in its own
//! module because a seed has to mean the same thing across workloads: the fuzz
//! and probe corpora are compared against each other, and two copies of the
//! recurrence, however identical they look today, are two things that can be
//! tuned apart and silently stop being the same corpus.
//!
//! Not a crypto RNG and never to be used as one. Nothing here is unpredictable
//! to anyone holding the seed, which is the entire point.

pub(crate) struct Rng(u64);

impl Rng {
    pub(crate) fn new(seed: u64) -> Self {
        // A zero state is a fixed point for xorshift, so it would emit zero
        // forever and every case would be identical.
        Self(if seed == 0 { 0x9E3779B97F4A7C15 } else { seed })
    }

    pub(crate) fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545F4914F6CDD1D)
    }

    pub(crate) fn below(&mut self, n: usize) -> usize {
        (self.next() % n.max(1) as u64) as usize
    }

    /// One element of `xs`, uniformly enough for a corpus.
    ///
    /// Panics on an empty slice, which is a bug in the caller's table rather
    /// than an input condition: every corpus table in this crate is a literal.
    pub(crate) fn pick<'a, T>(&mut self, xs: &'a [T]) -> &'a T {
        &xs[self.below(xs.len())]
    }

    /// Fill `out` with generated bytes.
    pub(crate) fn bytes(&mut self, out: &mut [u8]) {
        for chunk in out.chunks_mut(8) {
            let word = self.next().to_le_bytes();
            chunk.copy_from_slice(&word[..chunk.len()]);
        }
    }
}
