//! Tests for the parts of the harness that are pure.
//!
//! The workloads need a daemon and are exercised by running them. What is
//! testable here is the accounting and the reporting, and both matter: a
//! percentile that is off by one rank, or a report that renders a failure as a
//! pass, would make every run wrong in a way nobody would notice.

use std::time::Duration;

use crate::report::Report;
use crate::stats::{Latencies, Throughput};

/// Nearest-rank percentiles, checked against a distribution whose answers are
/// known by hand. An off-by-one in the rank calculation is the defect this
/// catches, and it is the easiest one to introduce.
#[test]
fn percentiles_pick_a_sample_that_was_actually_measured() {
    let mut l = Latencies::new();
    for i in 1..=100u64 {
        l.record(Duration::from_micros(i));
    }
    let s = l.summary().expect("100 samples summarise");
    assert_eq!(s.count, 100);
    assert_eq!(s.min_us, 1);
    assert_eq!(s.max_us, 100);
    assert_eq!(s.p50_us, 50);
    assert_eq!(s.p95_us, 95);
    assert_eq!(s.p99_us, 99);
    assert_eq!(s.mean_us, 50); // 5050 / 100, truncated.
}

/// A single sample must report itself at every quantile rather than indexing
/// past the end of a one-element distribution.
#[test]
fn one_sample_is_its_own_every_percentile() {
    let mut l = Latencies::new();
    l.record(Duration::from_micros(7));
    let s = l.summary().expect("one sample summarises");
    assert_eq!((s.min_us, s.p50_us, s.p99_us, s.max_us), (7, 7, 7, 7));
}

/// An empty collector must report nothing. Zeros would be read as "instant" and
/// quoted as a result, which is worse than an absent number.
#[test]
fn an_empty_collector_reports_nothing_rather_than_zero() {
    assert!(Latencies::new().summary().is_none());
}

/// Merging is how per-connection collectors become a total, so it must keep
/// every sample rather than replacing or averaging.
#[test]
fn merging_keeps_every_sample_from_both_sides() {
    let mut a = Latencies::new();
    let mut b = Latencies::new();
    a.record(Duration::from_micros(1));
    a.record(Duration::from_micros(3));
    b.record(Duration::from_micros(100));
    a.merge(&b);
    let s = a.summary().expect("three samples");
    assert_eq!(s.count, 3);
    assert_eq!(s.max_us, 100);
    assert_eq!(s.p50_us, 3);
}

/// A zero-length window must not report infinite throughput. Division by the
/// elapsed time is the obvious implementation and it produces `inf`, which then
/// serialises as JSON `null` and silently loses the measurement.
#[test]
fn a_zero_length_window_reports_zero_rather_than_infinity() {
    let t = Throughput::new(1024, 8, Duration::ZERO);
    assert_eq!(t.bytes_per_sec, 0.0);
    assert_eq!(t.messages_per_sec, 0.0);
    assert_eq!(t.bytes, 1024, "the totals are still reported");
}

#[test]
fn throughput_divides_by_the_measured_window() {
    let t = Throughput::new(2048, 10, Duration::from_secs(2));
    assert_eq!(t.bytes_per_sec, 1024.0);
    assert_eq!(t.messages_per_sec, 5.0);
}

/// A report with failures must say so in both renderings. This is the check that
/// keeps a red run from reading as green.
#[test]
fn a_report_with_a_failure_renders_as_failed() {
    let mut r = Report::new("load", "ws://x/ws", serde_json::json!({ "sessions": 2 }));
    assert!(!r.failed());
    assert!(r.markdown().contains("verdict: passed"));

    r.failures.push("delivery shortfall: 1 byte of 2".to_string());
    assert!(r.failed());
    let md = r.markdown();
    assert!(md.contains("verdict: FAILED"), "{md}");
    assert!(md.contains("delivery shortfall"), "{md}");
}

/// The Markdown is a rendering of the JSON, so a number present in one must be
/// present in the other. A report whose prose and data disagree is worse than
/// either alone.
#[test]
fn the_markdown_shows_the_numbers_the_json_carries() {
    let mut r = Report::new("load", "ws://host/ws", serde_json::json!({ "sessions": 3 }));
    r.duration_secs = 1.5;
    r.throughput = Some(Throughput::new(4096, 12, Duration::from_secs(4)));
    let mut l = Latencies::new();
    l.record(Duration::from_micros(250));
    r.latencies
        .push(("create_session".to_string(), l.summary().unwrap()));
    r.checks_passed.push("every generated byte arrived".to_string());

    let md = r.markdown();
    assert!(md.contains("ws://host/ws"), "{md}");
    assert!(md.contains("1.50s"), "{md}");
    assert!(md.contains("create_session"), "{md}");
    assert!(md.contains("250"), "{md}");
    assert!(md.contains("every generated byte arrived"), "{md}");
    assert!(md.contains("\"sessions\": 3"), "{md}");

    // And the JSON round trips, because it is the record the Markdown renders.
    let back: Report = serde_json::from_str(&serde_json::to_string(&r).unwrap()).unwrap();
    assert_eq!(back.latencies, r.latencies);
    assert_eq!(back.duration_secs, 1.5);
}

/// Two runs of the same workload must not land in the same directory, or the
/// second would overwrite the first.
#[test]
fn a_report_writes_json_and_markdown_into_its_own_directory() {
    let dir = std::env::temp_dir().join(format!("vitrum-bench-test-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let r = Report::new("fuzz", "ws://x/ws", serde_json::Value::Null);
    let out = r.write(&dir).expect("writing a report");
    assert!(out.join("report.json").is_file());
    assert!(out.join("report.md").is_file());
    assert!(
        out.starts_with(&dir) && out != dir,
        "the report went to {} rather than a subdirectory",
        out.display()
    );
    let written: Report =
        serde_json::from_slice(&std::fs::read(out.join("report.json")).unwrap()).unwrap();
    assert_eq!(written.run_id, r.run_id);
    let _ = std::fs::remove_dir_all(&dir);
}

/// The generated load command must produce exactly the byte count the delivery
/// check expects, because that check is the only thing that turns "bytes
/// arrived" into "the right bytes arrived".
///
/// Captured through a pipe, so this sees the payload width. On a pty the kernel
/// translates the newline to CR LF, which is the one extra byte per line that
/// [`crate::load::LINE_BYTES`] accounts for.
/// Runs `/bin/sh`, which is the shell the daemon spawns the generator with, so
/// this only runs where that shell exists. Faking it elsewhere would test a
/// different command from the one the workload sends.
#[cfg(unix)]
#[test]
fn the_load_generator_emits_the_width_the_delivery_check_assumes() {
    let out = std::process::Command::new("/bin/sh")
        .arg("-c")
        .arg(crate::load::generator(5))
        .output()
        .expect("running the generator");
    assert!(out.status.success(), "{:?}", out.status);
    let piped_width = crate::load::LINE_BYTES - 1;
    assert_eq!(
        out.stdout.len(),
        5 * piped_width,
        "the generator wrote {} bytes for 5 lines of {piped_width}",
        out.stdout.len(),
    );
    assert_eq!(out.stdout.iter().filter(|&&b| b == b'\n').count(), 5);
    assert!(
        !out.stdout.contains(&b'\r'),
        "the generator itself must not emit CR; the pty adds it"
    );
}

// --- world geometry & shape -------------------------------------------------
//
// The world workload needs a daemon to run, but its geometry model and its
// session shapes are pure, and they are the part a reviewer should be able to
// trust without a live server: the smallest-wins convergence check reads these
// numbers, so a wrong min here makes the whole convergence claim hollow.

/// Windows are monotonically non-narrower, and the narrowest is window 0.
/// Identical geometry between two windows would let the convergence rule pass
/// without ever being exercised, so distinct windows must want distinct sizes.
#[test]
fn world_windows_are_distinct_and_narrowest_first() {
    let (c0, r0) = crate::world::geometry(0, 120);
    assert_eq!((c0, r0), (80, 24));
    let (c1, r1) = crate::world::geometry(1, 120);
    assert_eq!((c1, r1), (90, 32));
    assert_ne!(
        crate::world::geometry(0, 120),
        crate::world::geometry(2, 120),
        "two windows at the same size would not test convergence"
    );
}

/// The converged geometry is the per-axis minimum over all windows, which is
/// exactly what the daemon claims to enforce. Round-trip the stated rule so a
/// drift in the ceiling, not the death, fails the test.
#[test]
fn world_smallest_geometry_is_the_narrowest_window() {
    let widest = 100;
    let narrow = crate::world::smallest_geometry(4, widest);
    let mut cols = u16::MAX;
    let mut rows = u16::MAX;
    for w in 0..4 {
        let (c, r) = crate::world::geometry(w, widest);
        cols = cols.min(c);
        rows = rows.min(r);
    }
    assert_eq!(narrow, (cols, rows));
    assert!(narrow.0 >= 80 && narrow.1 >= 24, "geometry never shrinks below the floor");
}

/// The burst command is `/bin/sh`, the riddle is a bare `/bin/cat`, and both
/// are distinct — the workload depends on the riddle being the one session
/// that echoes input back.
#[test]
fn world_command_shapes_are_what_the_phases_expect() {
    let (sh, args) = crate::world::burst_command(10);
    assert_eq!(sh, "/bin/sh");
    assert_eq!(args[0], "-c");
    assert!(args[1].contains(&format!("-le 10")), "emits exactly its line budget");

    let (cat, cat_args) = crate::world::riddle_command();
    assert_eq!(cat, "/bin/cat");
    assert!(cat_args.is_empty(), "a bare cat never terminates and echoes input");

    let (ssh, ssh_args) = crate::world::ssh_command("somehost.example", 42);
    assert_eq!(ssh, "/usr/bin/ssh");
    assert!(ssh_args.contains(&"--".to_string()), "`--` stops flag parsing for the remote argv");
    assert!(ssh_args.iter().any(|a| a.contains("somehost.example")));
}
