//! Tests for the parts of the harness that are pure.
//!
//! The workloads need a daemon and are exercised by running them. What is
//! testable here is the accounting and the reporting, and both matter: a
//! percentile that is off by one rank, or a report that renders a failure as a
//! pass, would make every run wrong in a way nobody would notice.

use std::time::Duration;

use crate::report::Report;
use crate::stats::{Latencies, Throughput};

/// Nearest-rank percentiles, checked against a distribution whose answers are
/// known by hand. An off-by-one in the rank calculation is the defect this
/// catches, and it is the easiest one to introduce.
#[test]
fn percentiles_pick_a_sample_that_was_actually_measured() {
    let mut l = Latencies::new();
    for i in 1..=100u64 {
        l.record(Duration::from_micros(i));
    }
    let s = l.summary().expect("100 samples summarise");
    assert_eq!(s.count, 100);
    assert_eq!(s.min_us, 1);
    assert_eq!(s.max_us, 100);
    assert_eq!(s.p50_us, 50);
    assert_eq!(s.p95_us, 95);
    assert_eq!(s.p99_us, 99);
    assert_eq!(s.mean_us, 50); // 5050 / 100, truncated.
}

/// A single sample must report itself at every quantile rather than indexing
/// past the end of a one-element distribution.
#[test]
fn one_sample_is_its_own_every_percentile() {
    let mut l = Latencies::new();
    l.record(Duration::from_micros(7));
    let s = l.summary().expect("one sample summarises");
    assert_eq!((s.min_us, s.p50_us, s.p99_us, s.max_us), (7, 7, 7, 7));
}

/// An empty collector must report nothing. Zeros would be read as "instant" and
/// quoted as a result, which is worse than an absent number.
#[test]
fn an_empty_collector_reports_nothing_rather_than_zero() {
    assert!(Latencies::new().summary().is_none());
}

/// Merging is how per-connection collectors become a total, so it must keep
/// every sample rather than replacing or averaging.
#[test]
fn merging_keeps_every_sample_from_both_sides() {
    let mut a = Latencies::new();
    let mut b = Latencies::new();
    a.record(Duration::from_micros(1));
    a.record(Duration::from_micros(3));
    b.record(Duration::from_micros(100));
    a.merge(&b);
    let s = a.summary().expect("three samples");
    assert_eq!(s.count, 3);
    assert_eq!(s.max_us, 100);
    assert_eq!(s.p50_us, 3);
}

/// A zero-length window must not report infinite throughput. Division by the
/// elapsed time is the obvious implementation and it produces `inf`, which then
/// serialises as JSON `null` and silently loses the measurement.
#[test]
fn a_zero_length_window_reports_zero_rather_than_infinity() {
    let t = Throughput::new(1024, 8, Duration::ZERO);
    assert_eq!(t.bytes_per_sec, 0.0);
    assert_eq!(t.messages_per_sec, 0.0);
    assert_eq!(t.bytes, 1024, "the totals are still reported");
}

#[test]
fn throughput_divides_by_the_measured_window() {
    let t = Throughput::new(2048, 10, Duration::from_secs(2));
    assert_eq!(t.bytes_per_sec, 1024.0);
    assert_eq!(t.messages_per_sec, 5.0);
}

/// A report with failures must say so in both renderings. This is the check that
/// keeps a red run from reading as green.
#[test]
fn a_report_with_a_failure_renders_as_failed() {
    let mut r = Report::new("load", "ws://x/ws", serde_json::json!({ "sessions": 2 }));
    assert!(!r.failed());
    assert!(r.markdown().contains("verdict: passed"));

    r.failures.push("delivery shortfall: 1 byte of 2".to_string());
    assert!(r.failed());
    let md = r.markdown();
    assert!(md.contains("verdict: FAILED"), "{md}");
    assert!(md.contains("delivery shortfall"), "{md}");
}

/// The Markdown is a rendering of the JSON, so a number present in one must be
/// present in the other. A report whose prose and data disagree is worse than
/// either alone.
#[test]
fn the_markdown_shows_the_numbers_the_json_carries() {
    let mut r = Report::new("load", "ws://host/ws", serde_json::json!({ "sessions": 3 }));
    r.duration_secs = 1.5;
    r.throughput = Some(Throughput::new(4096, 12, Duration::from_secs(4)));
    let mut l = Latencies::new();
    l.record(Duration::from_micros(250));
    r.latencies
        .push(("create_session".to_string(), l.summary().unwrap()));
    r.checks_passed.push("every generated byte arrived".to_string());

    let md = r.markdown();
    assert!(md.contains("ws://host/ws"), "{md}");
    assert!(md.contains("1.50s"), "{md}");
    assert!(md.contains("create_session"), "{md}");
    assert!(md.contains("250"), "{md}");
    assert!(md.contains("every generated byte arrived"), "{md}");
    assert!(md.contains("\"sessions\": 3"), "{md}");

    // And the JSON round trips, because it is the record the Markdown renders.
    let back: Report = serde_json::from_str(&serde_json::to_string(&r).unwrap()).unwrap();
    assert_eq!(back.latencies, r.latencies);
    assert_eq!(back.duration_secs, 1.5);
}

/// Two runs of the same workload must not land in the same directory, or the
/// second would overwrite the first.
#[test]
fn a_report_writes_json_and_markdown_into_its_own_directory() {
    let dir = std::env::temp_dir().join(format!("vitrum-bench-test-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let r = Report::new("fuzz", "ws://x/ws", serde_json::Value::Null);
    let out = r.write(&dir).expect("writing a report");
    assert!(out.join("report.json").is_file());
    assert!(out.join("report.md").is_file());
    assert!(
        out.starts_with(&dir) && out != dir,
        "the report went to {} rather than a subdirectory",
        out.display()
    );
    let written: Report =
        serde_json::from_slice(&std::fs::read(out.join("report.json")).unwrap()).unwrap();
    assert_eq!(written.run_id, r.run_id);
    let _ = std::fs::remove_dir_all(&dir);
}

/// The generated load command must produce exactly the byte count the delivery
/// check expects, because that check is the only thing that turns "bytes
/// arrived" into "the right bytes arrived".
///
/// Captured through a pipe, so this sees the payload width. On a pty the kernel
/// translates the newline to CR LF, which is the one extra byte per line that
/// [`crate::load::LINE_BYTES`] accounts for.
/// Runs `/bin/sh`, which is the shell the daemon spawns the generator with, so
/// this only runs where that shell exists. Faking it elsewhere would test a
/// different command from the one the workload sends.
#[cfg(unix)]
#[test]
fn the_load_generator_emits_the_width_the_delivery_check_assumes() {
    let out = std::process::Command::new("/bin/sh")
        .arg("-c")
        .arg(crate::load::generator(5))
        .output()
        .expect("running the generator");
    assert!(out.status.success(), "{:?}", out.status);
    let piped_width = crate::load::LINE_BYTES - 1;
    assert_eq!(
        out.stdout.len(),
        5 * piped_width,
        "the generator wrote {} bytes for 5 lines of {piped_width}",
        out.stdout.len(),
    );
    assert_eq!(out.stdout.iter().filter(|&&b| b == b'\n').count(), 5);
    assert!(
        !out.stdout.contains(&b'\r'),
        "the generator itself must not emit CR; the pty adds it"
    );
}

// --- world geometry & shape -------------------------------------------------
//
// The world workload needs a daemon to run, but its geometry model and its
// session shapes are pure, and they are the part a reviewer should be able to
// trust without a live server: the smallest-wins convergence check reads these
// numbers, so a wrong min here makes the whole convergence claim hollow.

/// Windows are monotonically non-narrower, and the narrowest is window 0.
/// Identical geometry between two windows would let the convergence rule pass
/// without ever being exercised, so distinct windows must want distinct sizes.
#[test]
fn world_windows_are_distinct_and_narrowest_first() {
    let (c0, r0) = crate::world::geometry(0, 120);
    assert_eq!((c0, r0), (80, 24));
    let (c1, r1) = crate::world::geometry(1, 120);
    assert_eq!((c1, r1), (90, 32));
    assert_ne!(
        crate::world::geometry(0, 120),
        crate::world::geometry(2, 120),
        "two windows at the same size would not test convergence"
    );
}

/// The converged geometry is the per-axis minimum over all windows, which is
/// exactly what the daemon claims to enforce. Round-trip the stated rule so a
/// drift in the ceiling, not the death, fails the test.
#[test]
fn world_smallest_geometry_is_the_narrowest_window() {
    let widest = 100;
    let narrow = crate::world::smallest_geometry(4, widest);
    let mut cols = u16::MAX;
    let mut rows = u16::MAX;
    for w in 0..4 {
        let (c, r) = crate::world::geometry(w, widest);
        cols = cols.min(c);
        rows = rows.min(r);
    }
    assert_eq!(narrow, (cols, rows));
    assert!(narrow.0 >= 80 && narrow.1 >= 24, "geometry never shrinks below the floor");
}

/// The burst command is `/bin/sh`, the riddle is a bare `/bin/cat`, and both
/// are distinct — the workload depends on the riddle being the one session
/// that echoes input back.
#[test]
fn world_scripts_are_what_the_phases_expect() {
    let burst = crate::world::burst_script(10);
    assert!(burst.contains("-le 10"), "emits exactly its line budget");

    let riddle = crate::world::riddle_script();
    assert_eq!(riddle, "exec /bin/cat", "a bare cat never terminates and echoes input");

    let ssh = crate::world::ssh_script("somehost.example", 42);
    assert!(ssh.contains(" -- "), "`--` stops flag parsing for the remote argv");
    assert!(ssh.contains("somehost.example"));
    assert!(ssh.contains("-le 42"), "the remote emits the line budget, not the local shell");
}

/// The remote command survives the shell that carries it.
///
/// The generator contains single quotes, which is the case that breaks naive
/// quoting: pasted in raw they close the quoting around the remote command and
/// the tail of it runs on the wrong machine. Asserting on the quoted string
/// would only restate the implementation, so a shell is asked what it sees.
#[cfg(unix)]
#[test]
fn a_quoted_remote_command_reaches_the_shell_unchanged() {
    for original in [
        crate::load::generator(3),
        "it's got 'several' quotes".to_string(),
        "$(echo substituted) `echo too`".to_string(),
    ] {
        let out = std::process::Command::new("/bin/sh")
            .arg("-c")
            .arg(format!("printf %s {}", crate::world::sh_quote(&original)))
            .output()
            .expect("run a shell");
        assert_eq!(
            String::from_utf8_lossy(&out.stdout),
            original,
            "the shell saw something other than the command we quoted"
        );
    }
}

// --- the frame probe --------------------------------------------------------
//
// WHY: these close the class "a frame phase stops being attributed". A phase
// added to the enum without a place in `Phase::ALL` would index past the
// accumulator, and a phase in `ALL` with no call site would report as free.
// The first is caught here; the second is caught by `frame::run`, which fails
// the run when a phase records nothing. What neither catches is a phase whose
// span brackets the wrong region — that is a judgement, and the run's
// sum-against-the-frame check is the only thing that constrains it.

/// Every phase indexes a distinct slot inside the accumulator, and no phase
/// indexes past it.
///
/// The variant space is read from `Phase::ALL` rather than listed here, so a
/// new phase that is not added to `ALL` fails this instead of silently
/// overrunning the array at run time.
#[test]
fn every_frame_phase_owns_one_slot_in_the_accumulator() {
    use vitrum_grid::probe::Phase;

    let mut seen = vec![false; Phase::ALL.len()];
    for phase in Phase::ALL {
        let mut frame = vitrum_grid::probe::Frame::default();
        assert_eq!(frame.nanos(phase), 0);
        assert_eq!(frame.calls(phase), 0);
        // Distinctness through the accessor, because the index is private and
        // the accessor is what the report reads.
        frame = record(phase);
        let hits: Vec<&'static str> = Phase::ALL
            .iter()
            .filter(|p| frame.calls(**p) > 0)
            .map(|p| p.name())
            .collect();
        assert_eq!(
            hits,
            vec![phase.name()],
            "{} shares a slot with another phase",
            phase.name()
        );
        let slot = Phase::ALL.iter().position(|p| *p == phase).expect("in ALL");
        assert!(!seen[slot], "{} appears twice in ALL", phase.name());
        seen[slot] = true;
    }
    assert!(seen.into_iter().all(|s| s), "a slot in ALL is unreachable");
}

/// One span of `phase`, recorded and taken. Serialised by the probe's own
/// process-wide switch, so these tests cannot interleave with each other.
fn record(phase: vitrum_grid::probe::Phase) -> vitrum_grid::probe::Frame {
    use vitrum_grid::probe;
    let _guard = PROBE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    probe::reset();
    probe::set_enabled(true);
    {
        let _span = probe::span(phase);
    }
    probe::set_enabled(false);
    probe::take()
}

static PROBE_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// The switch is what "off by default" means at run time: a span taken while
/// it is off must record nothing at all, or an idle frame would be charged for
/// a measurement nobody asked for.
#[test]
fn a_span_taken_with_the_probe_off_records_nothing() {
    use vitrum_grid::probe::{self, Phase};

    let _guard = PROBE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    probe::set_enabled(false);
    probe::reset();
    {
        let _span = probe::span(Phase::Parse);
        std::thread::sleep(Duration::from_millis(1));
    }
    assert!(
        probe::take().is_empty(),
        "the probe recorded a span while it was switched off"
    );
}

/// A build runs either the control arm or the two probe arms, never a mixture.
/// The comparator joins rounds by arm name and would pair an arm with itself if
/// one binary could produce both.
#[test]
fn a_build_offers_the_control_arm_or_the_probe_arms_but_not_both() {
    use crate::frame::Arm;

    let arms = Arm::compiled();
    assert!(!arms.is_empty());
    let control = arms.contains(&Arm::Absent);
    let probed = arms.contains(&Arm::Off) || arms.contains(&Arm::On);
    assert!(control ^ probed, "a build offered {arms:?}");
    if probed {
        assert!(
            arms.contains(&Arm::Off) && arms.contains(&Arm::On),
            "the zero-cost comparison needs both switch positions from one build"
        );
    }
}

// --- divergence -------------------------------------------------------------
//
// WHY: a fuzzer that cannot fail turns every clean run into a claim nobody
// checked. These gate the detector itself, and the corpus that records what it
// has found.

/// The comparison really does fail on a screen that is different.
///
/// One byte apart is the smallest difference that matters, and the whole value
/// of a clean `divergence` run rests on this: without it, "twenty thousand
/// inputs agreed" and "the comparison always returns None" are the same
/// report.
#[test]
fn the_differential_detector_fails_on_a_screen_that_really_differs() {
    let a = b"hello world";
    let b = b"hellp world";
    let how = crate::divergence::differential(a, b, &[4])
        .expect("both paths run")
        .expect("a one-byte difference is a different screen");
    assert!(how.contains("cell"), "{how}");

    assert!(
        crate::divergence::differential(a, a, &[4])
            .expect("both paths run")
            .is_none(),
        "the same bytes fed two ways produced two screens"
    );
}

/// A split falling inside a multi-byte character must not change the screen.
/// This is the case the whole chunking axis exists for, pinned as a case rather
/// than left to the seed.
#[test]
fn a_split_inside_a_character_does_not_change_the_screen() {
    let text = "日本語 ── 🙂".as_bytes();
    for at in 1..text.len() {
        assert!(
            crate::divergence::chunking(text, &[at])
                .expect("both paths run")
                .is_none(),
            "splitting at byte {at} changed the screen"
        );
    }
}

/// Threads driving their own sessions produce the screens they produce alone,
/// under an interleaving and free-running alike.
#[test]
fn concurrent_sessions_produce_the_screens_they_produce_alone() {
    let work: Vec<Vec<Vec<u8>>> = vec![
        vec![b"\x1b[31mred\r\n".to_vec(), b"more\r\n".to_vec()],
        vec![b"\x1b[1mbold".to_vec(), b"\x1b[0m tail\r\n".to_vec()],
    ];
    let steps = vec![1, 0, 1, 0];
    assert!(
        crate::divergence::concurrent(&work, Some(&steps))
            .expect("the scheduled run completes")
            .is_none()
    );
    assert!(
        crate::divergence::concurrent(&work, None)
            .expect("the free run completes")
            .is_none()
    );
}

/// Every committed artefact replays to the status recorded for it.
///
/// Both directions are checked. An `open` artefact that stops reproducing means
/// the defect was fixed and nobody updated the record; a `fixed` artefact that
/// reproduces means the fix was undone. Either way the corpus is stale, and a
/// stale corpus is the same as no corpus.
#[test]
fn every_committed_artefact_replays_to_its_recorded_status() {
    use crate::divergence::{Status, corpus};

    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("artifacts");
    for (path, artifact) in corpus(&dir).expect("the committed corpus parses") {
        let name = path.display();
        match (artifact.status(), artifact.replay().expect("replaying")) {
            (Status::Open, Some(_)) | (Status::Fixed, None) => {}
            (Status::Open, None) => {
                panic!("{name} is recorded as open but no longer reproduces; record the fix")
            }
            (Status::Fixed, Some(how)) => {
                panic!("{name} is recorded as fixed but diverged again: {how}")
            }
        }
    }
}

/// An artefact survives the round trip through the file it is committed as, and
/// names itself the same way twice.
#[test]
fn an_artefact_round_trips_through_its_file_and_keeps_its_name() {
    use crate::divergence::{Artifact, Status};

    let artifact = Artifact::Chunking {
        status: Status::Fixed,
        note: "cell (0, 0) differed".to_string(),
        input_hex: "1b5b306d61".to_string(),
        splits: vec![2],
    };
    let text = serde_json::to_string(&artifact).expect("serialising");
    let back: Artifact = serde_json::from_str(&text).expect("parsing");
    assert_eq!(back, artifact);
    assert_eq!(back.file_name(), artifact.file_name());
    assert!(artifact.file_name().starts_with("chunking-"));
}

// --- the world's floor ------------------------------------------------------

/// Whether the floor is subtracted depends on this classification, so a URL
/// read wrongly publishes a figure with someone else's hops taken out of it.
#[test]
fn only_a_daemon_on_this_machine_has_the_locally_measured_floor() {
    use crate::world::server_is_local;

    for local in [
        "ws://127.0.0.1:7777/ws",
        "ws://localhost:7777/ws",
        "ws://127.0.0.1/ws",
        "ws://127.0.1.9:7777/ws",
        "ws://[::1]:7777/ws",
    ] {
        assert!(server_is_local(local), "{local} is on this machine");
    }
    for remote in [
        "ws://198.51.100.7:7777/ws",
        "ws://rig.example:7777/ws",
        "wss://vitrum.example/ws",
        "ws://127x0.example:7777/ws",
        "ws://[fd00::1]:7777/ws",
    ] {
        assert!(!server_is_local(remote), "{remote} is not on this machine");
    }
}

/// Subtracting the floor keeps every sample and never produces a negative
/// latency. A sample below the floor means the two measurements disagreed by
/// less than their own noise, which is a zero, not a number below zero read
/// back as an enormous unsigned one.
#[test]
fn subtracting_the_floor_saturates_and_keeps_every_sample() {
    let net = crate::world::subtract(&[10_000, 5_000, 100], 5_000).expect("three samples");
    assert_eq!(net.count, 3);
    assert_eq!(net.min, 0, "a sample under the floor is zero, not underflow");
    assert_eq!(net.max, 5_000);
}
